name: PlanetCraftSSG
version: 1.1.0
main: nl.jerskisnow.planetcraftssg.Main
description: Official PlanetCraftSSG Plugin
author: jerskisnow
api-version: 1.13
depend: [WorldEdit, WorldGuard, Vault]
commands:
  time:
    usage: /<command>
    aliases:
    - onlinetime
  staffchat:
    usage: /<command>
    aliases:
    - staffc
  credits:
    usage: /<command>
    aliases:
    - credit
  country:
    usage: /<command>
    aliases: 
    - ctry
  report:
    usage: /<command>
  chatcolor:
    usage: /<command>
    aliases:
    - cc
    - chatc
    - ccolor
  staffmode:
    usage: /<command>
    aliases:
    - sm
    - staffm
    - smode
  trademenu:
    usage: /<command>
    aliases:
    - tradeshop
    - opentrademenu
    - opentradeshop